name: Build AML Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download AML Headers
      run: |
        git clone https://github.com/RusJJ/AndroidModLoader.git temp_aml
        cp -r temp_aml/mod .
        rm -rf temp_aml

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c

    - name: Compile Mod for 32-bit (Android)
      run: |
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-21 ..
        make

    - name: Upload Mod File
      uses: actions/upload-artifact@v4
      with:
        name: MyFirstMod-32bit
        path: build/libMyFirstMod.so
        
